version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: adonis_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adonis_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis_app
    depends_on:
      - mysql
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3333:3333'
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: adonis_db
    command: sh ./entrypoint.sh

  gateway-mocks:
    image: matheusprotzen/gateways-mock
    container_name: adonis_gateway_mocks
    ports:
      - '3001:3001'
      - '3002:3002'
    environment:
      REMOVE_AUTH: 'false'

volumes:
  mysql_data:
